name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        python-version: [3.7, 3.8]
        tox_env: [py-orange-released]
        experimental: [false]
        include:
          - os: windows-latest
            python-version: 3.7
            tox_env: py-orange-oldest
            experimental: false
          - os: macOS-latest
            python-version: 3.7
            tox_env: py-orange-oldest
            experimental: false
          - os: ubuntu-latest
            python-version: 3.7
            tox_env: py-orange-oldest
            experimental: false

          - os: windows-latest
            python-version: 3.8
            tox_env: py-orange-latest
            experimental: false
          - os: macOS-latest
            python-version: 3.8
            tox_env: py-orange-latest
            experimental: false
          - os: ubuntu-latest
            python-version: 3.8
            tox_env: py-orange-latest
            experimental: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox tox-pip-version

      - name: Test with Tox
        run: |
          tox -e ${{ matrix.tox_env }}
        env:
          QT_QPA_PLATFORM: offscreen

      - name: Upload code coverage
        if: |
          matrix.python-version == '3.8' &&  
          matrix.os == 'ubuntu-latest' && 
          matrix.tox_env == 'py-orange-released'
        run: |
          pip install codecov
          codecov
